### ISSUE TITLE
Question: Dispose CrmServiceClient on Clone

### ISSUE THREAD

**Issue by mathiasbl** [seanmcne/XrmCoreLibrary#44]
https://github.com/seanmcne/XrmCoreLibrary/blob/0608b7a41ef2f174afcaf7c450a1d01dcb652607/v9/Client/XrmServiceManager.cs#L307

What is the exact reason to dispose the newly created CrmServiceClient while is it still used as a return value?

**Comment by seanmcne** [comment]
@mathiasbl fantastic observation on your part!  I’m already in the process of reversing this change (I haven’t yet pushed it to GitHub 😀 but I’ll do that in the near future). After testing and looking at it again I also had concluded it doesn’t make sense to dispose inside of XrmServiceManager.

**Comment by seanmcne** [comment]
@mathiasbl apologies as this totally fell off my radar - the build on nuget has been updated for some time but the source wasn't sync'd up here.  Thanks for taking the time to reach out!
