### ISSUE TITLE
.Net Core

### ISSUE THREAD

**Issue by DanielHolth** [seanmcne/XrmCoreLibrary#46]
Hi

Observing how Azure function app, Power Platform and Common Data Service are all moving towards .Net Core (instead of .Net Framework). It is a pleasure to see that D365 XRM SDK functionality is also adapting .Net Core through Microsofts latest nugget. Will you also add this to your roadmap?

Link:
https://www.nuget.org/packages/Microsoft.Powerplatform.Cds.Client

**Comment by seanmcne** [comment]
Yep, would be happy to once it gets closer to release it's still in alpha and things are a bit in flux still.  Looking forward to a core compatible release though - thanks!
