### ISSUE TITLE
The operation timed out

### ISSUE THREAD

**Issue by eduardoed5** [seanmcne/XrmCoreLibrary#48]
We are executing bulk client shipping using the ParallelProxy.Execute function. but when it is done, it sends us the following error:

**_The request channel timed out while waiting for a response after 00: 00: 09.9199895. Increase the timeout value passed to the Request call, or increase the SendTimeout value on the binding. The time allotted for this operation may have been a part of a longer wait time._**

We have set the options as follows to extend the response time, but the error continues to present. We are sending 5000 records in the test.

```
var options = new OrganizationServiceProxyOptions()
            {
                Timeout = new TimeSpan(0, 40, 0)
            };
IDictionary<string, ExecuteMultipleResponse> result = service.ParallelProxy.Execute<ExecuteMultipleRequest, ExecuteMultipleResponse>(collectionRequest, options);
```

What could be happening.

**Comment by seanmcne** [comment]
Hi Eduardo, I'm sorry this somehow got missed in my emails.  Are you still running into the issue?
