### ISSUE TITLE
 Microsoft.IdentityModel.Clients.ActiveDirectory.dll NULL when insert rows in Dynamics 365 from windows service c#

### ISSUE THREAD

**Issue by Rcdo07** [seanmcne/XrmCoreLibrary#49]
I have a program to insert rows in Dynamics 365 instance. The program runs well when i use a console app, but with the same code runs in a Windows Service program, when insert a row, show this error:

![image](https://user-images.githubusercontent.com/74463815/99681560-42b56f80-2a4c-11eb-8de1-7be6b0cba927.png)

Error:  InnerException = {Microsoft.IdentityModel.Clients.ActiveDirectory.dll":null}   HResult: -2146233088

Any help to resolve this problem?

**Comment by seanmcne** [comment]
Try running a procmon to see if it's trying to load ADAL and can't? Maybe adal isn't in the same folder as the service.  A second idea is to make sure you're using a service principal/connection string that doesn't require 2FA. 

can you share an example of your connection string used or how you're connecting using crmserviceclient (be sure to omit any secrets from it). Thx!

**Comment by Rcdo07** [comment]
Hi,
This code is for connect to CRM Instance:

var connectionString = @"AuthType=OAuth;Url=https://xxxxxxx.crm.dynamics.com; Username=test@contoso.onmicrosoft.com; Password=xxxxx; AppId=00000000-0000-0000-0000-000000000000; RedirectUri=app://00000000-0000-0000-0000-0900000000000; LoginPrompt=Never" />

CrmServiceClient conn = new CrmServiceClient(connectionString);

return new OrganizationServiceManager(conn);

Later, i use this OrganizationServiceManager to execute multiple insert in CRM (_servicio is the return from the connection)

var options = new OrganizationServiceProxyOptions()
               {

                   Timeout = new TimeSpan(0, 40, 0)

               };

               IDictionary<string, ExecuteMultipleResponse> _resultadoPeticion = _servicio.ParallelProxy.Execute<ExecuteMultipleRequest, ExecuteMultipleResponse>(_colleccionBloques, options);

               _callback(_resultadoPeticion, _colleccionBloques, _log, nombreTabla, nombreCampoEstado, nombreAtributoLlave, nombreColumnaLlave, GuardarSQL);

**Comment by seanmcne** [comment]
can you confirm the dll in question is also in the same directory as your app/bin directory when it's registered as a windows service?  Off hand it looks like it can't load or find the dll - many times using processmonitor from sysinternals can help you diagnose why it can't find the dll.

**Comment by yogeshkoshti4313** [comment]
I've a WebAPI project and in another class library I'm using CRM services. I'm getting below exception if you could help me to fix this.

I tried using different ways to connect CRMClient
1. Using connection string
2.Using username & password

![image](https://user-images.githubusercontent.com/12621786/124606035-81acff80-de3a-11eb-829f-48961b354b4a.png)

![image](https://user-images.githubusercontent.com/12621786/124606150-98ebed00-de3a-11eb-87b3-ffaea618bc5d.png)

**Comment by yutianncsu** [comment]
Have the same issue when trying to connect to the Cloud D365 from the asp.net page or windows service.  Please suggest some solution for this issue.

**Comment by yutianncsu** [comment]
More details:
My ADAL is null, but the code in the Organization service manager Class:
FileVersionInfo fvi = FileVersionInfo.GetVersionInfo("Microsoft.IdentityModel.Clients.ActiveDirectory.dll") can't find the dll without the full path. 

I am able to find the DLL with the path like:
 System.IO.Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, System.AppDomain.CurrentDomain.RelativeSearchPath ?? "")+ @"\Microsoft.IdentityModel.Clients.ActiveDirectory.dll"

but the simple "\Microsoft.IdentityModel.Clients.ActiveDirectory.dll" is not working for my FileVersionInfo.GetVersionInfo function. 

Please kindly suggest some solution how to make ADAL not null or make the function  FileVersionInfo.GetVersionInfo() working as expected.

Code from Nuget:

protected Microsoft.Xrm.Tooling.Connector.CrmServiceClient GetProxy<CrmServiceClient>()
        {
            if (this.ServiceClient.ActiveAuthenticationType != Microsoft.Xrm.Tooling.Connector.AuthenticationType.ExternalTokenManagement)
            {
                if (AdalVersion == null)
                {
                    **FileVersionInfo fvi = FileVersionInfo.GetVersionInfo("Microsoft.IdentityModel.Clients.ActiveDirectory.dll");**
                    AdalVersion = fvi;
                }

                if (AdalVersion != null
                    && (AdalVersion.FileMajorPart != 2 && AdalVersion.FileMajorPart != 3))
                {
                    XrmCoreEventSource.Log.LogError($"ADAL Version {AdalVersion.FileVersion} is not matching the expected versions of 2.x or 3.x. Certain functions may not work as expected if you're not using the AuthOverrideHook.");
                }
            }

**Comment by seanmcne** [comment]
I assume this is .NET Framework 4.6+ ? 

Run procmon when you launch your process, it should be able to locate the adal DLL, as far as I know all the recent versions of CrmServiceClient (XRM Tooling) require ADAL.  Which version of crmserviceclient are you using?

**Comment by yutianncsu** [comment]
@seanmcne Thanks for the reply. 
This is the .NET Framework 4.6.2.

I am using XRM Tooling version 9.1.0.79. I think this is installed automatically when I install the Pfe.Microsoft.Xrm.CoreV9. 

I try to run the procmon when I debug my ASP.Net Page on my localhost, but I am new to the procmon, can you please kindly share some idea how I can locate the adal DLL. Thanks in adavnced.

**Comment by seanmcne** [comment]
To look for any kind of bug I wanted to try testing locally. To do so I created a brand new .NET console app in Visual Studio 2019 from scratch and here's the steps I took on my PC: 
1. Created a new project 
2. set the version to 4.6.2 as you did here 
3. Installed the core lib from Nuget which pulls in all the minimum versions & dependencies: 
![image](https://user-images.githubusercontent.com/2292260/127005248-93497a4f-9be1-485c-bca7-cab37c2bc28e.png)

4. Wrote the following code 
![image](https://user-images.githubusercontent.com/2292260/127021387-bd6f8dc4-4f6e-48b9-b7f5-e4395850a4d4.png)

5. Ran that same code by pressing F5 this successfully connected to the service 

What I see in my bin\Debug folder (with no modifications): 
![image](https://user-images.githubusercontent.com/2292260/127022317-7d3feac6-0d76-4fec-865e-e67c2a51e9cb.png)

I'm curious if you follow the same steps above if you're able to have a working project, that may help figure out why you're not having a similar result in your other project.

**Comment by yutianncsu** [comment]
Thanks for the reply. 
I created a new project follow your steps. 
The console application is working and able to run the .ParallelProxy.RetrieveMultiple() Method without any issue.

But when I added the Asp.Net project under the same solution and using the same code to test, I got the Microsoft.IdentityModel.Clients.ActiveDirectory.dll NULL  Error again.

I doubt there is some problem for the Asp.Net solution or windows service project to locate this DLL with the GetProxy() function.

Can you please kindly try to add the asp.net or windows service project under your solution to see if you can replicate the issue. Thanks.

**Comment by LeoXrm** [comment]
I'm also having the same issue in my Web application project. For info, the console app or unit test are working fine: 
![image](https://user-images.githubusercontent.com/48332333/133489119-0a78fd87-cc04-496c-8cf5-9f2dbd56f9ec.png)

And here is the list of the DLLs: 
![image](https://user-images.githubusercontent.com/48332333/133489690-391ebf12-0e6e-4fab-bccc-4ad900a78345.png)

**Comment by LeoXrm** [comment]
@seanmcne @yutianncsu @Rcdo07 I believe the real issue is that the `FileVersionInfo fvi = FileVersionInfo.GetVersionInfo("Microsoft.IdentityModel.Clients.ActiveDirectory.dll");` code throws the exception in an ASP .NET application. If we can somehow disable it or catching exception, I think the library will work for ASP .NET and hopefully for a Windows service as well. 
Best,

![image](https://user-images.githubusercontent.com/48332333/133501102-92736e9b-ed48-4771-9430-de0e2a2d0935.png)

**Comment by yutianncsu** [comment]
@LeoXrm 
Yes, I download the code and updated the GetVersionInfo Part to
System.IO.Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, System.AppDomain.CurrentDomain.RelativeSearchPath ?? "")+ @"\Microsoft.IdentityModel.Clients.ActiveDirectory.dll"

Then the new DLL is working with my windows service and Asp.Net application. I am using that DLL as a workaround now. Hope the new version can fix this issue.

**Comment by seanmcne** [comment]
Thanks for the comments, I made some updates today to catch and handle the filenotfound exception - let me know if this addresses the problem well enough. Apologies for the long delay in response!
