### ISSUE TITLE
Update nuget package with latest commit

### ISSUE THREAD

**Issue by mohsinonxrm** [seanmcne/XrmCoreLibrary#50]
Hi @seanmcne , can you please release/update the nuget package with the fixes/updates from the latest commit:
https://github.com/seanmcne/XrmCoreLibrary/commit/c03009a73b12c20555133af90498f56020fc3152

**Comment by mohsinonxrm** [comment]
@seanmcne , just wanted to follow-up on this.

**Comment by seanmcne** [comment]
@mohsinonxrm - I need to double check, but I am fairly certain the existing version should cover this, are you not seeing that?  The built-in using was a mistake and shouldn't have gone to nuget - that commit referenced was to revert the change made.

**Comment by mohsinonxrm** [comment]
@seanmcne , looking for the following line # 284 to be in the release:
|| this.ServiceClient.ActiveAuthenticationType == Microsoft.Xrm.Tooling.Connector.AuthenticationType.ClientSecret

Current package doesn't work when using ClientSecret AuthType connection string.
<add name="MyCDSServer" 
  connectionString="
  AuthType=ClientSecret;
  url=https://contosotest.crm.dynamics.com;
  ClientId={AppId};
  ClientSecret={ClientSecret}"
  />

**Comment by mohsinonxrm** [comment]
@seanmcne , friendly reminder on this. Can I expect this to be released/updated this week? If not, that's fine too, just need to plan updates on my side.

**Comment by seanmcne** [comment]
I have it all integrated and building / tested etc - looking to try and get it released this week.

**Comment by mohsinonxrm** [comment]
> I have it all integrated and building / tested etc - looking to try and get it released this week.

Thank you @seanmcne !

**Comment by seanmcne** [comment]
we should be in good shape now from the looks of it: 
https://www.nuget.org/packages/Pfe.Microsoft.Xrm.CoreV9/9.0.7

**Comment by mohsinonxrm** [comment]
@seanmcne , all good. closing this out. thanks for updating the package.
